export const adminCopy = {
  nav: {
    dashboard: 'Admin',
    negocios: 'Negocios',
    lugares: 'Lugares',
    comisiones: 'Comisiones',
    categorias: 'Categorías',
  },

  dashboard: {
    title: 'Panel de administración',
    pendingAlert: 'negocios pendientes de aprobación',
    stats: {
      pendingBusinesses: 'Pendientes',
      activeBusinesses: 'Activos',
      totalBookings: 'Reservas totales',
      totalLugares: 'Lugares turísticos',
      commissionRate: 'Comisión experiencias',
    },
    sections: {
      businesses: 'Gestión de negocios',
      businessesDesc: 'Aprobar o rechazar negocios registrados',
      lugares: 'Lugares turísticos',
      lugaresDesc: 'Crear y editar atracciones de Manaure',
      commissions: 'Tasas de comisión',
      commissionsDesc: 'Ajustar el porcentaje cobrado por servicio',
    },
  },

  negocios: {
    title: 'Negocios',
    subtitle: 'Aprueba, rechaza y gestiona los negocios registrados en la plataforma.',
    new: 'Nuevo negocio',
    approve: 'Aprobar',
    reject: 'Rechazar',
    forceDeactivate: 'Desactivar',
    forceActivate: 'Reactivar',
    filter: {
      pending: 'Pendientes',
      active: 'Activos',
      inactive: 'Inactivos',
      rejected: 'Rechazados',
    },
    owner: 'Propietario',
    createdAt: 'Registrado',
    empty: 'No hay negocios en este estado.',
    feature: 'Destacar',
    unfeature: 'Quitar destacado',
    form: {
      title: 'Crear negocio',
      name: 'Nombre del negocio',
      namePlaceholder: 'Ej: Balneario Las Palmeras',
      type: 'Tipo',
      description: 'Descripción',
      descriptionPlaceholder: 'Describe el negocio...',
      address: 'Dirección',
      addressPlaceholder: 'Ej: Calle 5 #10-20, Manaure',
      phone: 'Teléfono',
      phonePlaceholder: 'Ej: 3001234567',
      owner: 'Propietario',
      ownerPlaceholder: '— Selecciona un propietario —',
      ownerEmpty: 'No hay usuarios con rol business_owner registrados.',
      submit: 'Crear negocio',
      submitting: 'Creando...',
      cancel: 'Cancelar',
      backToList: 'Volver a negocios',
      errors: {
        nameRequired: 'El nombre es obligatorio.',
        typeRequired: 'Selecciona un tipo.',
        ownerRequired: 'Selecciona un propietario.',
        generic: 'Error al crear el negocio. Intenta de nuevo.',
      },
    },
    statusColors: {
      pending:  'bg-accent/15 text-accent',
      active:   'bg-primary/15 text-primary',
      rejected: 'bg-destructive/15 text-destructive',
      inactive: 'bg-muted text-muted-foreground',
    } as Record<string, string>,
    statusLabels: {
      pending: 'Pendiente',
      active: 'Activo',
      rejected: 'Rechazado',
      inactive: 'Inactivo',
    } as Record<string, string>,
  },

  comisiones: {
    title: 'Tasas de comisión',
    subtitle: 'Porcentaje que retiene ManTur sobre el monto total de cada transacción.',
    serviceType: {
      experience: 'Experiencias',
      transport: 'Transporte',
      business: 'Negocios',
    } as Record<string, string>,
    rateLabel: 'Tasa (%)',
    save: 'Guardar',
    saving: 'Guardando...',
    success: 'Tasa actualizada correctamente.',
    errors: {
      invalidRate: 'La tasa debe ser un número entre 0 y 100.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Configuración no encontrada.',
    },
  },

  lugares: {
    title: 'Lugares turísticos',
    subtitle: 'Atracciones y puntos de interés de Manaure Balcón del Cesar.',
    new: 'Nuevo lugar',
    edit: 'Editar',
    delete: 'Eliminar',
    empty: 'Aún no hay lugares registrados.',
    form: {
      name: 'Nombre',
      namePlaceholder: 'Ej: Balneario La Danta',
      description: 'Descripción',
      descriptionPlaceholder: 'Describe el lugar...',
      type: 'Tipo',
      lat: 'Latitud',
      latPlaceholder: 'Ej: 11.7808',
      lng: 'Longitud',
      lngPlaceholder: 'Ej: -72.9944',
      submit: 'Guardar lugar',
      submitting: 'Guardando...',
      cancel: 'Cancelar',
      backToList: 'Volver a lugares',
    },
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      typeRequired: 'Selecciona un tipo.',
      invalidCoords: 'Las coordenadas deben ser números válidos.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Lugar no encontrado.',
      deleteError: 'Error al eliminar.',
    },
  },

  categorias: {
    title: 'Categorías de negocios',
    subtitle: 'Gestiona los tipos de negocio disponibles para registro.',
    new: 'Nueva categoría',
    namePlaceholder: 'Ej: Cabaña',
    slugPlaceholder: 'Ej: cabana',
    add: 'Agregar',
    adding: 'Agregando...',
    empty: 'No hay categorías registradas.',
    activate: 'Activar',
    deactivate: 'Desactivar',
    delete: 'Eliminar',
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      slugRequired: 'El slug es obligatorio.',
      slugFormat: 'El slug solo puede contener letras, números y guiones bajos.',
      slugTaken: 'Ya existe una categoría con ese slug.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Categoría no encontrada.',
      deleteError: 'No se puede eliminar. Intenta desactivarla en su lugar.',
    },
    dashboard: {
      sections: {
        categories: 'Categorías de negocios',
        categoriesDesc: 'Agregar o desactivar tipos de negocio disponibles',
      },
    },
  },

  errors: {
    unauthorized: 'No autorizado.',
  },
}
