export const adminCopy = {
  solicitudes: {
    title: 'Solicitudes de rol',
    subtitle: 'Revisa y gestiona las solicitudes de cambio de rol de los usuarios.',
    empty: 'No hay solicitudes en este estado.',
    filter: {
      pending: 'Pendientes',
      approved: 'Aprobadas',
      rejected: 'Rechazadas',
    },
    roles: {
      business_owner: 'Dueño de negocio',
      transporter: 'Transportador',
      tourist_guide: 'Guía turístico',
    },
    approve: 'Aprobar',
    reject: 'Rechazar',
    rejectionReasonLabel: 'Motivo del rechazo',
    rejectionReasonPlaceholder: 'Explica al usuario por qué se rechaza la solicitud...',
    submittedAt: 'Solicitado',
    reviewedAt: 'Revisado',
    rejectedBecause: 'Motivo:',
    metaLabels: {
      business_name: 'Negocio',
      categories: 'Categorías',
      phone: 'Teléfono',
      license_plate: 'Placa',
      vehicle_type: 'Vehículo',
      specialties: 'Especialidades',
      languages: 'Idiomas',
      experience_years: 'Años de experiencia',
      bio: 'Presentación',
      rnt_number: 'RNT',
      tarjeta_profesional_number: 'Tarjeta profesional',
      transport_tier: 'Modalidad',
      cooperative_name: 'Cooperativa',
      cooperative_rnt_number: 'RNT cooperativa',
      cooperative_habilitacion_number: 'Habilitación Mintransporte',
      driver_license_number: 'Licencia de conducción',
      driver_license_expiry: 'Vencimiento licencia',
      soat_expiry_date: 'Vencimiento SOAT',
    },
    transportTierLabels: {
      cooperative: 'Cooperativa formal',
      independent: 'Conductor independiente',
    } as Record<string, string>,
    viewDocument: 'Ver documento',
    documentUnavailable: 'No se pudo abrir el documento.',
  },

  dashboard: {
    title: 'Panel de administración',
    subtitle: 'Resumen de actividad de la plataforma',
    stats: {
      pendingBusinesses: 'Pendientes',
      activeBusinesses: 'Activos',
      totalBookings: 'Reservas totales',
      totalLugares: 'Lugares turísticos',
      commissionRate: 'Comisión actividades/tours',
      totalRevenue: 'Ingresos confirmados',
      netMargin: 'Margen neto real (comisión − Wompi)',
      failedPayments: 'Pagos fallidos',
      pendingInvoices: 'Facturas pendientes de conciliación DIAN',
      registeredUsers: 'Usuarios registrados',
      activeGuides: 'Guías activos',
      activeTransporters: 'Transportistas activos',
    },
    sections: {
      pendingApprovals: 'En espera de aprobación',
      pendingApprovalsEmpty: 'Sin negocios pendientes',
      recentBookings: 'Reservas recientes',
      recentBookingsEmpty: 'Sin reservas aún',
      viewAll: 'Ver todos',
      financialHealth: 'Salud financiera',
      growth: 'Crecimiento y oferta',
      bookingsByStatus: 'Reservas por estado',
    },
    attention: {
      title: 'Necesita tu atención',
      empty: 'Todo al día. No hay pendientes en las colas operativas.',
      items: {
        stuckPayouts: 'Pagos a proveedores atascados',
        pendingRefunds: 'Reembolsos pendientes',
        pendingBusinesses: 'Negocios pendientes de aprobación',
        pendingRoleRequests: 'Solicitudes de rol pendientes',
        pendingRnt: 'Negocios con RNT en revisión',
        pendingGuideVerification: 'Guías con verificación pendiente',
        pendingTransporterVerification: 'Transportistas con verificación pendiente',
      },
      stuckPayoutsHint: 'Requiere revisión manual en Supabase — sin reintento automático todavía.',
    },
    bookingStatus: {
      labels: {
        confirmed: 'Confirmada',
        pending_payment: 'En pago',
        completed: 'Completada',
        cancelled: 'Cancelada',
      } as Record<string, string>,
      colors: {
        confirmed: 'text-primary',
        pending_payment: 'text-amber-500',
        completed: 'text-muted-foreground',
        cancelled: 'text-destructive',
      } as Record<string, string>,
    },
    revenueTrendLabel: 'Últimos 14 días',
  },

  negocios: {
    title: 'Negocios',
    subtitle: 'Aprueba, rechaza y gestiona los negocios registrados en la plataforma.',
    new: 'Nuevo negocio',
    approve: 'Aprobar',
    reject: 'Rechazar',
    forceDeactivate: 'Desactivar',
    forceActivate: 'Reactivar',
    filter: {
      pending: 'Pendientes',
      active: 'Activos',
      inactive: 'Inactivos',
      rejected: 'Rechazados',
    },
    owner: 'Propietario',
    createdAt: 'Registrado',
    empty: 'No hay negocios en este estado.',
    feature: 'Destacar',
    unfeature: 'Quitar destacado',
    form: {
      title: 'Crear negocio',
      name: 'Nombre del negocio',
      namePlaceholder: 'Ej: Balneario Las Palmeras',
      type: 'Tipo',
      description: 'Descripción',
      descriptionPlaceholder: 'Describe el negocio...',
      address: 'Dirección',
      addressPlaceholder: 'Ej: Calle 5 #10-20, Manaure',
      location: 'Ubicación',
      locationHint: 'Tocá el mapa para marcar la ubicación exacta.',
      phone: 'Teléfono',
      phonePlaceholder: 'Ej: 3001234567',
      owner: 'Propietario',
      ownerPlaceholder: '— Selecciona un propietario —',
      ownerEmpty: 'No hay usuarios con rol business_owner registrados.',
      submit: 'Crear negocio',
      submitting: 'Creando...',
      cancel: 'Cancelar',
      backToList: 'Volver a negocios',
      errors: {
        nameRequired: 'El nombre es obligatorio.',
        typeRequired: 'Selecciona un tipo.',
        ownerRequired: 'Selecciona un propietario.',
        invalidPhone: 'Escribe un número de celular colombiano válido (10 dígitos, ej: 300 123 4567).',
        invalidCoords: 'Las coordenadas deben ser números válidos.',
        descriptionTooLong: 'La descripción no puede superar 1200 caracteres.',
        generic: 'Error al crear el negocio. Intenta de nuevo.',
      },
    },
    statusColors: {
      pending:  'bg-accent/15 text-accent',
      active:   'bg-primary/15 text-primary',
      rejected: 'bg-destructive/15 text-destructive',
      inactive: 'bg-muted text-muted-foreground',
    } as Record<string, string>,
    statusLabels: {
      pending: 'Pendiente',
      active: 'Activo',
      rejected: 'Rechazado',
      inactive: 'Inactivo',
    } as Record<string, string>,
    rnt: 'RNT',
    rntMissing: 'Sin RNT — no se puede aprobar hasta que el negocio lo suba.',
    rntStatusLabels: {
      pending_review: 'RNT en revisión',
      verified: 'RNT verificado',
      rejected: 'RNT rechazado',
    } as Record<string, string>,
    rntStatusColors: {
      pending_review: 'bg-accent/15 text-accent',
      verified: 'bg-primary/15 text-primary',
      rejected: 'bg-destructive/15 text-destructive',
    } as Record<string, string>,
    errors: {
      rntMissing: 'No se puede aprobar: el negocio todavía no ha subido su certificado RNT.',
    },
  },

  comisiones: {
    title: 'Tasas de comisión',
    subtitle: 'Porcentaje que retiene ManTur sobre el monto total de cada transacción.',
    serviceType: {
      tour_activity: 'Actividades/Tours',
      lodging: 'Hospedaje',
      event_rental: 'Alquiler para eventos',
      pasadia: 'Pasadía',
      guide_tour: 'Tours de guía',
      transport: 'Transporte',
      business: 'Negocios',
    } as Record<string, string>,
    rateLabel: 'Tasa (%)',
    save: 'Guardar',
    saving: 'Guardando...',
    success: 'Tasa actualizada correctamente.',
    errors: {
      invalidRate: 'La tasa debe ser un número entre 0 y 100.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Configuración no encontrada.',
    },
  },

  payoutAccounts: {
    label: 'ID de banco en Wompi',
    hint: 'Cópialo del catálogo de bancos de tu dashboard de Wompi (Pagos a Terceros).',
    save: 'Guardar',
    saving: 'Guardando...',
    success: 'ID de banco guardado.',
    noAccount: 'Aún no registró su cuenta bancaria.',
    errors: {
      invalidValue: 'Escribe un ID de banco válido.',
      notFound: 'El destinatario aún no ha registrado su cuenta bancaria.',
      generic: 'Error al guardar. Intenta de nuevo.',
    },
  },

  reembolsos: {
    title: 'Reembolsos',
    subtitle: 'Ventanas de reembolso y solicitudes de cancelación de turistas.',
    policyTitle: 'Ventanas de reembolso',
    policySubtitle: 'Porcentaje reembolsado según las horas restantes antes de la reserva.',
    policyTier: {
      '72': 'Con 72 horas o más de anticipación',
      '24': 'Entre 24 y 72 horas de anticipación',
      '0': 'Menos de 24 horas o no-show',
    } as Record<string, string>,
    rateLabel: 'Reembolso (%)',
    save: 'Guardar',
    saving: 'Guardando...',
    success: 'Ventana actualizada correctamente.',
    filter: {
      pending: 'Pendientes',
      processing: 'En proceso',
      processed: 'Procesados',
      rejected: 'Rechazados',
    } as Record<string, string>,
    empty: 'No hay solicitudes en este estado.',
    processingHint:
      'Reverso automático solicitado a Wompi, esperando su confirmación. Si tarda demasiado, puedes resolverlo manualmente.',
    requestedBy: 'Solicitado por',
    booking: 'Reserva',
    percentage: 'Porcentaje',
    amount: 'Monto',
    netAmount: 'Monto neto a transferir',
    grossAmount: 'Monto bruto',
    wompiFeeDeducted: 'Comisión Wompi retenida (no reembolsable)',
    processingManualFallbackNote:
      'Si Wompi confirma el reverso automático, el turista recibe el monto bruto completo sin descuentos. Si lo resuelves manualmente, se descuenta la comisión de Wompi del monto a enviar.',
    reason: 'Motivo del turista',
    payoutInstructions: 'Instrucciones de pago del turista',
    markProcessed: 'Marcar como procesado (manual)',
    reject: 'Rechazar',
    rejectionReasonPlaceholder: 'Explica por qué se rechaza este reembolso',
    method: {
      void: 'Reverso automático',
      manual: 'Transferencia manual',
    } as Record<string, string>,
    errors: {
      invalidRate: 'El porcentaje debe ser un número entre 0 y 100.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Configuración no encontrada.',
    },
  },

  pagosProveedores: {
    title: 'Pagos a proveedores atascados',
    subtitle:
      'Pagos a negocios o guías que no se completaron automáticamente. Puedes reintentar el envío o marcarlo como resuelto manualmente si ya se pagó por fuera del sistema.',
    empty: 'No hay pagos atascados en este momento.',
    recipient: 'Destinatario',
    amount: 'Monto',
    status: 'Estado',
    reason: 'Motivo',
    wompiReference: 'Referencia Wompi (transacción original)',
    payoutId: 'ID del pago (provider_payouts.id)',
    transactionId: 'ID de la transacción',
    since: 'Desde',
    resolvedBy: 'Resuelto por',
    unknownRecipient: 'Destinatario no encontrado',
    retry: 'Reintentar',
    sendingHint: 'Enviándose a Wompi ahora mismo — espera unos minutos antes de poder resolverlo manualmente.',
    resolveManually: 'Marcar como resuelto manualmente',
    resolveManuallyNotesPlaceholder: '¿Cómo se le pagó al proveedor? (transferencia, efectivo, etc.)',
    confirmResolveManually: 'Confirmar resolución',
    cancel: 'Cancelar',
    statusLabels: {
      pending: 'Pendiente (sin enviar)',
      sending: 'Enviando...',
      failed: 'Falló al enviarse',
    } as Record<string, string>,
    recipientTypeLabels: {
      business: 'Negocio',
      guide: 'Guía',
    } as Record<string, string>,
  },

  lugares: {
    title: 'Lugares turísticos',
    subtitle: 'Atracciones y puntos de interés de Manaure Balcón del Cesar.',
    new: 'Nuevo lugar',
    edit: 'Editar',
    delete: 'Eliminar',
    empty: 'Aún no hay lugares registrados.',
    confirmDeleteTitle: 'Eliminar lugar',
    confirmDeleteDescription:
      'Esta acción no se puede deshacer. El lugar y sus fotos y videos se eliminarán permanentemente.',
    confirmDeleteConfirm: 'Sí, eliminar',
    confirmDeleteCancel: 'Cancelar',
    form: {
      name: 'Nombre',
      namePlaceholder: 'Ej: Balneario La Danta',
      description: 'Descripción',
      descriptionPlaceholder: 'Describe el lugar...',
      type: 'Tipo',
      location: 'Ubicación',
      locationHint: 'Tocá el mapa para marcar la ubicación exacta.',
      submit: 'Guardar lugar',
      submitting: 'Guardando...',
      cancel: 'Cancelar',
      backToList: 'Volver a lugares',
    },
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      typeRequired: 'Selecciona un tipo.',
      invalidCoords: 'Las coordenadas deben ser números válidos.',
      descriptionTooLong: 'La descripción no puede superar 1200 caracteres.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Lugar no encontrado.',
      deleteError: 'Error al eliminar.',
    },
  },

  paquetes: {
    title: 'Paquetes/Tours',
    subtitle: 'Inventario propio de ManTur como operador turístico.',
    new: 'Nuevo paquete',
    edit: 'Editar',
    delete: 'Eliminar',
    activate: 'Activar',
    deactivate: 'Desactivar',
    empty: 'Aún no hay paquetes registrados.',
    confirmDeleteTitle: 'Eliminar paquete',
    confirmDeleteDescription: 'Esta acción no se puede deshacer.',
    confirmDeleteConfirm: 'Sí, eliminar',
    confirmDeleteCancel: 'Cancelar',
    statusLabels: {
      active: 'Activo',
      inactive: 'Inactivo',
    } as Record<string, string>,
    media: {
      title: 'Fotos y videos',
      hint: 'La primera foto es la imagen principal del paquete.',
      errors: {
        maxExceeded: 'Máximo 10 fotos y videos por paquete.',
        imageRequired: 'Selecciona una imagen.',
        invalidImageType: 'Formato no válido. Usa JPEG, PNG o WebP.',
        imageTooLarge: 'La imagen no puede superar 5 MB.',
        uploadFailed: 'No se pudo subir la imagen. Intenta de nuevo.',
        saveFailed: 'No se pudo guardar la imagen.',
        invalidVideoType: 'Formato no válido. Usa MP4, WebM o QuickTime.',
        videoTooLarge: 'El video no puede superar 50 MB.',
        videoUploadFailed: 'No se pudo iniciar la subida del video. Intenta de nuevo.',
        invalidVideo: 'Video no válido.',
        videoSaveFailed: 'No se pudo guardar el video.',
      },
    },
    form: {
      name: 'Nombre',
      namePlaceholder: 'Ej: Ruta Serranía del Perijá',
      description: 'Descripción',
      descriptionPlaceholder: 'Describe el paquete, qué incluye, el itinerario...',
      basePrice: 'Precio de venta al turista (COP)',
      pricingUnit: 'Se cobra',
      pricingUnitOptions: {
        per_person: 'Por persona',
        per_night: 'Por noche',
        fixed: 'Precio fijo',
      } as Record<string, string>,
      capacity: 'Cupo máximo (opcional)',
      submit: 'Guardar paquete',
      submitting: 'Guardando...',
      cancel: 'Cancelar',
      backToList: 'Volver a paquetes',
    },
    items: {
      title: 'Servicios y tours incluidos',
      subtitle:
        'El margen de ManTur es el precio de venta menos la suma de los costos internos de cada proveedor incluido.',
      empty: 'Este paquete todavía no incluye ningún servicio o tour.',
      providerLabel: 'Proveedor',
      servicesGroup: 'Servicios',
      guideToursGroup: 'Tours de guía',
      costLabel: 'Costo interno (COP)',
      quantityLabel: 'Cantidad incluida',
      add: 'Agregar',
      adding: 'Agregando...',
      remove: 'Quitar',
      selectPlaceholder: '— Selecciona un servicio o tour —',
      errors: {
        componentRequired: 'Selecciona un servicio o tour.',
        componentNotFound: 'El servicio o tour seleccionado ya no está disponible.',
        invalidCost: 'El costo interno debe ser un número válido.',
        invalidQuantity: 'La cantidad debe ser al menos 1.',
        generic: 'No se pudo agregar. Intenta de nuevo.',
      },
    },
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      invalidPrice: 'El precio de venta debe ser un número válido.',
      invalidPricingUnit: 'Selecciona cómo se cobra el paquete.',
      invalidCapacity: 'El cupo máximo debe ser un número entero mayor a 0.',
      descriptionTooLong: 'La descripción no puede superar 1200 caracteres.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Paquete no encontrado.',
      deleteError: 'Error al eliminar.',
      hasBookings: 'No se puede eliminar: este paquete ya tiene reservas. Desactívalo en su lugar.',
    },
    solicitudes: {
      title: 'Solicitudes de paquetes',
      subtitle: 'Confirma disponibilidad con cada proveedor antes de cobrar, y marca el pago una vez recibido.',
      pendingAvailabilityTitle: 'Disponibilidad pendiente',
      pendingPaymentTitle: 'Pago pendiente',
      emptyAvailability: 'No hay solicitudes esperando confirmación de disponibilidad.',
      emptyPayment: 'No hay reservas esperando confirmación de pago.',
      touristLabel: 'Turista',
      dateLabel: 'Fecha',
      quantityLabel: 'Personas/noches',
      totalLabel: 'Total',
      notesLabel: 'Notas del turista',
      includedTitle: 'Proveedores del paquete',
      markUnavailable: 'Marcar no disponible',
      markAvailable: 'Marcar disponible',
      unavailableBadge: 'No disponible',
      confirmAndCharge: 'Confirmar y pasar a pago',
      confirmChargeTitle: 'Confirmar disponibilidad',
      confirmChargeDescription: 'El turista será notificado y podrá proceder a pagar. Esta acción no se puede deshacer.',
      cancelRequest: 'Cancelar solicitud',
      confirmCancelTitle: 'Cancelar solicitud',
      confirmCancelDescription: 'El turista será notificado. Esta acción no se puede deshacer.',
      markPaid: 'Marcar como pagada',
      confirmMarkPaidTitle: 'Marcar como pagada',
      confirmMarkPaidDescription: 'Confirma que ya recibiste el pago de esta reserva. Esta acción no se puede deshacer.',
      whatsappContact: 'Escribir por WhatsApp',
      errors: {
        notFound: 'Reserva no encontrada.',
        invalidBookingState: 'Esta reserva ya no está en el estado esperado. Actualiza la página.',
        providerUnavailable: 'Aún hay proveedores marcados como no disponibles para esta fecha.',
        generic: 'Ocurrió un error. Intenta de nuevo.',
      },
    },
  },

  categorias: {
    title: 'Categorías de negocios',
    subtitle: 'Gestiona los tipos de negocio disponibles para registro.',
    new: 'Nueva categoría',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej: Cabaña',
    slugPlaceholder: 'Ej: cabana',
    add: 'Agregar',
    adding: 'Agregando...',
    success: 'Categoría creada correctamente.',
    empty: 'No hay categorías registradas.',
    activate: 'Activar',
    deactivate: 'Desactivar',
    delete: 'Eliminar',
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      slugRequired: 'El slug es obligatorio.',
      slugFormat: 'El slug solo puede contener letras, números y guiones bajos.',
      slugTaken: 'Ya existe una categoría con ese slug.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Categoría no encontrada.',
      deleteError: 'No se puede eliminar. Intenta desactivarla en su lugar.',
    },
    dashboard: {
      sections: {
        categories: 'Categorías de negocios',
        categoriesDesc: 'Agregar o desactivar tipos de negocio disponibles',
      },
    },
  },

  tiposServicio: {
    title: 'Tipos de servicio',
    subtitle: 'Gestiona los tipos de servicio que los negocios pueden ofrecer.',
    new: 'Nuevo tipo de servicio',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej: Pasadía',
    pricingUnitLabel: 'Unidad de precio',
    pricingUnit: {
      per_person: 'Por persona',
      per_night: 'Por noche',
      fixed: 'Precio fijo',
    } as Record<string, string>,
    add: 'Agregar',
    adding: 'Agregando...',
    success: 'Tipo de servicio creado correctamente.',
    empty: 'No hay tipos de servicio registrados.',
    activate: 'Activar',
    deactivate: 'Desactivar',
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      pricingUnitRequired: 'La unidad de precio es obligatoria.',
      slugTaken: 'Ya existe un tipo de servicio con ese slug.',
      generic: 'Error al guardar. Intenta de nuevo.',
    },
  },

  guias: {
    title: 'Guías turísticos',
    subtitle: 'Verifica, desactiva o elimina guías registrados en la plataforma.',
    empty: 'No hay guías en este estado.',
    filter: {
      active: 'Activos',
      inactive: 'Desactivados',
    },
    statusLabels: {
      active: 'Activo',
      inactive: 'Desactivado',
    } as Record<string, string>,
    statusColors: {
      active: 'bg-primary/15 text-primary',
      inactive: 'bg-muted text-muted-foreground',
    } as Record<string, string>,
    available: 'Disponible',
    notAvailable: 'No disponible',
    deactivate: 'Desactivar',
    activate: 'Reactivar',
    delete: 'Eliminar',
    confirmDeactivateTitle: 'Desactivar guía',
    confirmDeactivateDescription:
      'El guía perderá acceso a su panel y dejará de aparecer en /guias hasta que un admin lo reactive. Útil si su Registro Nacional de Turismo venció o incumple las normas de la plataforma.',
    confirmDeactivateConfirm: 'Sí, desactivar',
    confirmDeleteTitle: 'Eliminar guía',
    confirmDeleteDescription:
      'Esta acción no se puede deshacer. Se eliminará el perfil y sus tours de forma permanente.',
    confirmDeleteConfirm: 'Sí, eliminar',
    confirmCancel: 'Cancelar',
    errors: {
      deleteBlocked: 'No se puede eliminar: tiene reservas asociadas. Desactívalo en su lugar.',
    },
    verification: {
      statusLabels: {
        pending_review: 'En revisión',
        verified: 'Verificado',
        rejected: 'Rechazado',
      } as Record<string, string>,
      statusColors: {
        pending_review: 'bg-accent/15 text-accent',
        verified: 'bg-primary/15 text-primary',
        rejected: 'bg-destructive/15 text-destructive',
      } as Record<string, string>,
      expired: 'Vencido',
      noDocuments: 'Sin documentos subidos',
      rntLabel: 'RNT',
      tarjetaLabel: 'Tarjeta profesional',
    },
  },

  transportistas: {
    title: 'Transportistas',
    subtitle: 'Verifica, desactiva o elimina transportadores registrados en la plataforma.',
    empty: 'No hay transportistas en este estado.',
    filter: {
      active: 'Activos',
      inactive: 'Desactivados',
    },
    statusLabels: {
      active: 'Activo',
      inactive: 'Desactivado',
    } as Record<string, string>,
    statusColors: {
      active: 'bg-primary/15 text-primary',
      inactive: 'bg-muted text-muted-foreground',
    } as Record<string, string>,
    available: 'Disponible',
    notAvailable: 'No disponible',
    deactivate: 'Desactivar',
    activate: 'Reactivar',
    delete: 'Eliminar',
    confirmDeactivateTitle: 'Desactivar transportista',
    confirmDeactivateDescription:
      'El transportista perderá acceso a su panel y dejará de aparecer en /transportistas hasta que un admin lo reactive. Útil si su documentación venció o incumple las normas de la plataforma.',
    confirmDeactivateConfirm: 'Sí, desactivar',
    confirmDeleteTitle: 'Eliminar transportista',
    confirmDeleteDescription:
      'Esta acción no se puede deshacer. Se eliminará el perfil de forma permanente.',
    confirmDeleteConfirm: 'Sí, eliminar',
    confirmCancel: 'Cancelar',
    errors: {
      deleteBlocked: 'No se puede eliminar: tiene traslados asociados. Desactívalo en su lugar.',
    },
    verification: {
      statusLabels: {
        pending_review: 'En revisión',
        verified: 'Verificado',
        rejected: 'Rechazado',
      } as Record<string, string>,
      statusColors: {
        pending_review: 'bg-accent/15 text-accent',
        verified: 'bg-primary/15 text-primary',
        rejected: 'bg-destructive/15 text-destructive',
      } as Record<string, string>,
      expired: 'Vencido',
      noDocuments: 'Sin documentos subidos',
      cooperativeLabel: 'Cooperativa',
      driverLicenseLabel: 'Licencia',
      soatLabel: 'SOAT',
    },
  },

  errors: {
    unauthorized: 'No autorizado.',
  },
}
