export const adminCopy = {
  solicitudes: {
    title: 'Solicitudes de rol',
    subtitle: 'Revisa y gestiona las solicitudes de cambio de rol de los usuarios.',
    empty: 'No hay solicitudes en este estado.',
    filter: {
      pending: 'Pendientes',
      approved: 'Aprobadas',
      rejected: 'Rechazadas',
    },
    roles: {
      business_owner: 'Dueño de negocio',
      transporter: 'Transportador',
      tourist_guide: 'Guía turístico',
    },
    approve: 'Aprobar',
    reject: 'Rechazar',
    rejectionReasonLabel: 'Motivo del rechazo',
    rejectionReasonPlaceholder: 'Explica al usuario por qué se rechaza la solicitud...',
    submittedAt: 'Solicitado',
    reviewedAt: 'Revisado',
    rejectedBecause: 'Motivo:',
    metaLabels: {
      business_name: 'Negocio',
      categories: 'Categorías',
      phone: 'Teléfono',
      license_plate: 'Placa',
      vehicle_type: 'Vehículo',
      specialties: 'Especialidades',
      languages: 'Idiomas',
      experience_years: 'Años de experiencia',
      bio: 'Presentación',
      rnt_number: 'RNT',
      tarjeta_profesional_number: 'Tarjeta profesional',
      transport_tier: 'Modalidad',
      cooperative_name: 'Cooperativa',
      cooperative_rnt_number: 'RNT cooperativa',
      cooperative_habilitacion_number: 'Habilitación Mintransporte',
      driver_license_number: 'Licencia de conducción',
      driver_license_expiry: 'Vencimiento licencia',
      soat_expiry_date: 'Vencimiento SOAT',
    },
    transportTierLabels: {
      cooperative: 'Cooperativa formal',
      independent: 'Conductor independiente',
    } as Record<string, string>,
    viewDocument: 'Ver documento',
    documentUnavailable: 'No se pudo abrir el documento.',
  },

  dashboard: {
    title: 'Panel de administración',
    pendingAlert: 'negocios pendientes de aprobación',
    stats: {
      pendingBusinesses: 'Pendientes',
      activeBusinesses: 'Activos',
      totalBookings: 'Reservas totales',
      totalLugares: 'Lugares turísticos',
      commissionRate: 'Comisión actividades/tours',
    },
    sections: {
      businesses: 'Gestión de negocios',
      businessesDesc: 'Aprobar o rechazar negocios registrados',
      lugares: 'Lugares turísticos',
      lugaresDesc: 'Crear y editar atracciones de Manaure',
      commissions: 'Tasas de comisión',
      commissionsDesc: 'Ajustar el porcentaje cobrado por servicio',
    },
  },

  negocios: {
    title: 'Negocios',
    subtitle: 'Aprueba, rechaza y gestiona los negocios registrados en la plataforma.',
    new: 'Nuevo negocio',
    approve: 'Aprobar',
    reject: 'Rechazar',
    forceDeactivate: 'Desactivar',
    forceActivate: 'Reactivar',
    filter: {
      pending: 'Pendientes',
      active: 'Activos',
      inactive: 'Inactivos',
      rejected: 'Rechazados',
    },
    owner: 'Propietario',
    createdAt: 'Registrado',
    empty: 'No hay negocios en este estado.',
    feature: 'Destacar',
    unfeature: 'Quitar destacado',
    form: {
      title: 'Crear negocio',
      name: 'Nombre del negocio',
      namePlaceholder: 'Ej: Balneario Las Palmeras',
      type: 'Tipo',
      description: 'Descripción',
      descriptionPlaceholder: 'Describe el negocio...',
      address: 'Dirección',
      addressPlaceholder: 'Ej: Calle 5 #10-20, Manaure',
      location: 'Ubicación',
      locationHint: 'Tocá el mapa para marcar la ubicación exacta.',
      phone: 'Teléfono',
      phonePlaceholder: 'Ej: 3001234567',
      owner: 'Propietario',
      ownerPlaceholder: '— Selecciona un propietario —',
      ownerEmpty: 'No hay usuarios con rol business_owner registrados.',
      submit: 'Crear negocio',
      submitting: 'Creando...',
      cancel: 'Cancelar',
      backToList: 'Volver a negocios',
      errors: {
        nameRequired: 'El nombre es obligatorio.',
        typeRequired: 'Selecciona un tipo.',
        ownerRequired: 'Selecciona un propietario.',
        invalidPhone: 'Escribe un número de celular colombiano válido (10 dígitos, ej: 300 123 4567).',
        invalidCoords: 'Las coordenadas deben ser números válidos.',
        descriptionTooLong: 'La descripción no puede superar 1200 caracteres.',
        generic: 'Error al crear el negocio. Intenta de nuevo.',
      },
    },
    statusColors: {
      pending:  'bg-accent/15 text-accent',
      active:   'bg-primary/15 text-primary',
      rejected: 'bg-destructive/15 text-destructive',
      inactive: 'bg-muted text-muted-foreground',
    } as Record<string, string>,
    statusLabels: {
      pending: 'Pendiente',
      active: 'Activo',
      rejected: 'Rechazado',
      inactive: 'Inactivo',
    } as Record<string, string>,
    rnt: 'RNT',
    rntMissing: 'Sin RNT — no se puede aprobar hasta que el negocio lo suba.',
    rntStatusLabels: {
      pending_review: 'RNT en revisión',
      verified: 'RNT verificado',
      rejected: 'RNT rechazado',
    } as Record<string, string>,
    rntStatusColors: {
      pending_review: 'bg-accent/15 text-accent',
      verified: 'bg-primary/15 text-primary',
      rejected: 'bg-destructive/15 text-destructive',
    } as Record<string, string>,
    errors: {
      rntMissing: 'No se puede aprobar: el negocio todavía no ha subido su certificado RNT.',
    },
  },

  comisiones: {
    title: 'Tasas de comisión',
    subtitle: 'Porcentaje que retiene ManTur sobre el monto total de cada transacción.',
    serviceType: {
      tour_activity: 'Actividades/Tours',
      lodging: 'Hospedaje',
      event_rental: 'Alquiler para eventos',
      pasadia: 'Pasadía',
      guide_tour: 'Tours de guía',
      transport: 'Transporte',
      business: 'Negocios',
    } as Record<string, string>,
    rateLabel: 'Tasa (%)',
    save: 'Guardar',
    saving: 'Guardando...',
    success: 'Tasa actualizada correctamente.',
    errors: {
      invalidRate: 'La tasa debe ser un número entre 0 y 100.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Configuración no encontrada.',
    },
  },

  payoutAccounts: {
    label: 'ID de banco en Wompi',
    hint: 'Cópialo del catálogo de bancos de tu dashboard de Wompi (Pagos a Terceros).',
    save: 'Guardar',
    saving: 'Guardando...',
    success: 'ID de banco guardado.',
    noAccount: 'Aún no registró su cuenta bancaria.',
    errors: {
      invalidValue: 'Escribe un ID de banco válido.',
      notFound: 'El destinatario aún no ha registrado su cuenta bancaria.',
      generic: 'Error al guardar. Intenta de nuevo.',
    },
  },

  reembolsos: {
    title: 'Reembolsos',
    subtitle: 'Ventanas de reembolso y solicitudes de cancelación de turistas.',
    policyTitle: 'Ventanas de reembolso',
    policySubtitle: 'Porcentaje reembolsado según las horas restantes antes de la reserva.',
    policyTier: {
      '72': 'Con 72 horas o más de anticipación',
      '24': 'Entre 24 y 72 horas de anticipación',
      '0': 'Menos de 24 horas o no-show',
    } as Record<string, string>,
    rateLabel: 'Reembolso (%)',
    save: 'Guardar',
    saving: 'Guardando...',
    success: 'Ventana actualizada correctamente.',
    filter: {
      pending: 'Pendientes',
      processing: 'En proceso',
      processed: 'Procesados',
      rejected: 'Rechazados',
    } as Record<string, string>,
    empty: 'No hay solicitudes en este estado.',
    processingHint:
      'Reverso automático solicitado a Wompi, esperando su confirmación. Si tarda demasiado, puedes resolverlo manualmente.',
    requestedBy: 'Solicitado por',
    booking: 'Reserva',
    percentage: 'Porcentaje',
    amount: 'Monto',
    reason: 'Motivo del turista',
    markProcessed: 'Marcar como procesado (manual)',
    reject: 'Rechazar',
    rejectionReasonPlaceholder: 'Explica por qué se rechaza este reembolso',
    method: {
      void: 'Reverso automático',
      manual: 'Transferencia manual',
    } as Record<string, string>,
    errors: {
      invalidRate: 'El porcentaje debe ser un número entre 0 y 100.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Configuración no encontrada.',
    },
  },

  lugares: {
    title: 'Lugares turísticos',
    subtitle: 'Atracciones y puntos de interés de Manaure Balcón del Cesar.',
    new: 'Nuevo lugar',
    edit: 'Editar',
    delete: 'Eliminar',
    empty: 'Aún no hay lugares registrados.',
    confirmDeleteTitle: 'Eliminar lugar',
    confirmDeleteDescription:
      'Esta acción no se puede deshacer. El lugar y sus fotos y videos se eliminarán permanentemente.',
    confirmDeleteConfirm: 'Sí, eliminar',
    confirmDeleteCancel: 'Cancelar',
    form: {
      name: 'Nombre',
      namePlaceholder: 'Ej: Balneario La Danta',
      description: 'Descripción',
      descriptionPlaceholder: 'Describe el lugar...',
      type: 'Tipo',
      location: 'Ubicación',
      locationHint: 'Tocá el mapa para marcar la ubicación exacta.',
      submit: 'Guardar lugar',
      submitting: 'Guardando...',
      cancel: 'Cancelar',
      backToList: 'Volver a lugares',
    },
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      typeRequired: 'Selecciona un tipo.',
      invalidCoords: 'Las coordenadas deben ser números válidos.',
      descriptionTooLong: 'La descripción no puede superar 1200 caracteres.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Lugar no encontrado.',
      deleteError: 'Error al eliminar.',
    },
  },

  categorias: {
    title: 'Categorías de negocios',
    subtitle: 'Gestiona los tipos de negocio disponibles para registro.',
    new: 'Nueva categoría',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej: Cabaña',
    slugPlaceholder: 'Ej: cabana',
    add: 'Agregar',
    adding: 'Agregando...',
    success: 'Categoría creada correctamente.',
    empty: 'No hay categorías registradas.',
    activate: 'Activar',
    deactivate: 'Desactivar',
    delete: 'Eliminar',
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      slugRequired: 'El slug es obligatorio.',
      slugFormat: 'El slug solo puede contener letras, números y guiones bajos.',
      slugTaken: 'Ya existe una categoría con ese slug.',
      generic: 'Error al guardar. Intenta de nuevo.',
      notFound: 'Categoría no encontrada.',
      deleteError: 'No se puede eliminar. Intenta desactivarla en su lugar.',
    },
    dashboard: {
      sections: {
        categories: 'Categorías de negocios',
        categoriesDesc: 'Agregar o desactivar tipos de negocio disponibles',
      },
    },
  },

  tiposServicio: {
    title: 'Tipos de servicio',
    subtitle: 'Gestiona los tipos de servicio que los negocios pueden ofrecer.',
    new: 'Nuevo tipo de servicio',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej: Pasadía',
    pricingUnitLabel: 'Unidad de precio',
    pricingUnit: {
      per_person: 'Por persona',
      per_night: 'Por noche',
      fixed: 'Precio fijo',
    } as Record<string, string>,
    add: 'Agregar',
    adding: 'Agregando...',
    success: 'Tipo de servicio creado correctamente.',
    empty: 'No hay tipos de servicio registrados.',
    activate: 'Activar',
    deactivate: 'Desactivar',
    errors: {
      nameRequired: 'El nombre es obligatorio.',
      pricingUnitRequired: 'La unidad de precio es obligatoria.',
      slugTaken: 'Ya existe un tipo de servicio con ese slug.',
      generic: 'Error al guardar. Intenta de nuevo.',
    },
  },

  guias: {
    title: 'Guías turísticos',
    subtitle: 'Verifica, desactiva o elimina guías registrados en la plataforma.',
    empty: 'No hay guías en este estado.',
    filter: {
      active: 'Activos',
      inactive: 'Desactivados',
    },
    statusLabels: {
      active: 'Activo',
      inactive: 'Desactivado',
    } as Record<string, string>,
    statusColors: {
      active: 'bg-primary/15 text-primary',
      inactive: 'bg-muted text-muted-foreground',
    } as Record<string, string>,
    available: 'Disponible',
    notAvailable: 'No disponible',
    deactivate: 'Desactivar',
    activate: 'Reactivar',
    delete: 'Eliminar',
    confirmDeactivateTitle: 'Desactivar guía',
    confirmDeactivateDescription:
      'El guía perderá acceso a su panel y dejará de aparecer en /guias hasta que un admin lo reactive. Útil si su Registro Nacional de Turismo venció o incumple las normas de la plataforma.',
    confirmDeactivateConfirm: 'Sí, desactivar',
    confirmDeleteTitle: 'Eliminar guía',
    confirmDeleteDescription:
      'Esta acción no se puede deshacer. Se eliminará el perfil y sus tours de forma permanente.',
    confirmDeleteConfirm: 'Sí, eliminar',
    confirmCancel: 'Cancelar',
    errors: {
      deleteBlocked: 'No se puede eliminar: tiene reservas asociadas. Desactívalo en su lugar.',
    },
    verification: {
      statusLabels: {
        pending_review: 'En revisión',
        verified: 'Verificado',
        rejected: 'Rechazado',
      } as Record<string, string>,
      statusColors: {
        pending_review: 'bg-accent/15 text-accent',
        verified: 'bg-primary/15 text-primary',
        rejected: 'bg-destructive/15 text-destructive',
      } as Record<string, string>,
      expired: 'Vencido',
      noDocuments: 'Sin documentos subidos',
      rntLabel: 'RNT',
      tarjetaLabel: 'Tarjeta profesional',
    },
  },

  transportistas: {
    title: 'Transportistas',
    subtitle: 'Verifica, desactiva o elimina transportadores registrados en la plataforma.',
    empty: 'No hay transportistas en este estado.',
    filter: {
      active: 'Activos',
      inactive: 'Desactivados',
    },
    statusLabels: {
      active: 'Activo',
      inactive: 'Desactivado',
    } as Record<string, string>,
    statusColors: {
      active: 'bg-primary/15 text-primary',
      inactive: 'bg-muted text-muted-foreground',
    } as Record<string, string>,
    available: 'Disponible',
    notAvailable: 'No disponible',
    deactivate: 'Desactivar',
    activate: 'Reactivar',
    delete: 'Eliminar',
    confirmDeactivateTitle: 'Desactivar transportista',
    confirmDeactivateDescription:
      'El transportista perderá acceso a su panel y dejará de aparecer en /transportistas hasta que un admin lo reactive. Útil si su documentación venció o incumple las normas de la plataforma.',
    confirmDeactivateConfirm: 'Sí, desactivar',
    confirmDeleteTitle: 'Eliminar transportista',
    confirmDeleteDescription:
      'Esta acción no se puede deshacer. Se eliminará el perfil de forma permanente.',
    confirmDeleteConfirm: 'Sí, eliminar',
    confirmCancel: 'Cancelar',
    errors: {
      deleteBlocked: 'No se puede eliminar: tiene traslados asociados. Desactívalo en su lugar.',
    },
    verification: {
      statusLabels: {
        pending_review: 'En revisión',
        verified: 'Verificado',
        rejected: 'Rechazado',
      } as Record<string, string>,
      statusColors: {
        pending_review: 'bg-accent/15 text-accent',
        verified: 'bg-primary/15 text-primary',
        rejected: 'bg-destructive/15 text-destructive',
      } as Record<string, string>,
      expired: 'Vencido',
      noDocuments: 'Sin documentos subidos',
      cooperativeLabel: 'Cooperativa',
      driverLicenseLabel: 'Licencia',
      soatLabel: 'SOAT',
    },
  },

  errors: {
    unauthorized: 'No autorizado.',
  },
}
