export const authCopy = {
  brand: {
    tagline: 'Turismo con alma local',
  },
  oauth: {
    google: 'Continuar con Google',
    divider: 'o continúa con',
  },
  login: {
    title: 'Ingresa a tu cuenta',
    subtitle: 'Descubre y reserva experiencias en Manaure',
    email: 'Correo electrónico',
    password: 'Contraseña',
    submit: 'Ingresar',
    noAccount: '¿No tienes cuenta?',
    signupLink: 'Regístrate',
    forgotPasswordLink: '¿Olvidaste tu contraseña?',
    resetSuccess: 'Tu contraseña fue actualizada. Inicia sesión con tu nueva contraseña.',
    errors: {
      invalidCredentials: 'Correo o contraseña incorrectos',
      generic: 'Ocurrió un error. Intenta de nuevo.',
      oauthFailed: 'No se pudo iniciar sesión con Google. Intenta de nuevo.',
      confirmFailed: 'El enlace de confirmación no es válido o ya expiró. Intenta registrarte de nuevo.',
      rateLimited: 'Demasiados intentos. Espera un momento e intenta de nuevo.',
    },
  },
  signup: {
    title: 'Crea tu cuenta',
    subtitle: 'Únete a la comunidad de ManTur',
    fullName: 'Nombre completo',
    email: 'Correo electrónico',
    password: 'Contraseña',
    roles: {
      tourist: 'Turista',
      business_owner: 'Dueño de negocio',
      transporter: 'Transportador (motocarro)',
    },
    submit: 'Crear cuenta',
    hasAccount: '¿Ya tienes cuenta?',
    loginLink: 'Inicia sesión',
    legalConsent: {
      prefix: 'Acepto los ',
      terms: 'Términos y Condiciones',
      middle: ' y autorizo el ',
      privacy: 'Tratamiento de mis datos personales',
      suffix: '.',
    },
    confirmationSent: {
      title: 'Revisa tu correo',
      body: 'Te enviamos un enlace para confirmar tu cuenta. Ábrelo desde tu correo para poder iniciar sesión.',
    },
    passwordRules: {
      title: 'Tu contraseña requiere:',
      minLength: 'Mínimo 8 caracteres',
      uppercase: 'Una letra mayúscula',
      digit: 'Un número',
      special: 'Un carácter especial',
    },
    errors: {
      emailInUse: 'Este correo ya está registrado',
      weakPassword: 'La contraseña no cumple los requisitos de seguridad',
      nameRequired: 'El nombre es obligatorio.',
      invalidName: 'El nombre solo puede contener letras y espacios.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
      rateLimited: 'Demasiados intentos. Espera un momento e intenta de nuevo.',
    },
  },
  forgotPassword: {
    title: 'Recupera tu contraseña',
    subtitle: 'Te enviaremos un enlace para restablecerla',
    email: 'Correo electrónico',
    submit: 'Enviar enlace',
    backToLogin: 'Volver a iniciar sesión',
    confirmationSent: {
      title: 'Revisa tu correo',
      body: 'Si existe una cuenta con ese correo, te enviamos un enlace para restablecer tu contraseña.',
    },
    errors: {
      emailRequired: 'Ingresa tu correo electrónico.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
      rateLimited: 'Demasiados intentos. Espera un momento e intenta de nuevo.',
      expiredLink: 'El enlace no es válido o ya expiró. Solicita uno nuevo.',
    },
  },
  resetPassword: {
    title: 'Crea una nueva contraseña',
    subtitle: 'Elige una contraseña segura para tu cuenta',
    password: 'Nueva contraseña',
    confirmPassword: 'Confirmar contraseña',
    submit: 'Guardar contraseña',
    errors: {
      weakPassword: 'La contraseña no cumple los requisitos de seguridad',
      passwordMismatch: 'Las contraseñas no coinciden',
      sessionExpired: 'El enlace no es válido o ya expiró. Solicita uno nuevo.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
    },
  },
} as const
