export const bookingsCopy = {
  form: {
    title: 'Reservar experiencia',
    date: 'Fecha',
    datePlaceholder: 'Selecciona una fecha',
    people: 'Número de personas',
    peoplePlaceholder: 'Ej: 2',
    totalLabel: 'Total a pagar',
    perPerson: 'por persona',
    submit: 'Confirmar reserva',
    submitting: 'Procesando...',
    cancel: 'Cancelar',
  },

  confirmation: {
    titleConfirmed: '¡Reserva confirmada!',
    titlePending: 'Reserva en proceso',
    titleCancelled: 'Reserva cancelada',
    subtitleConfirmed: 'Tu reserva fue registrada exitosamente.',
    subtitlePending: 'Tu pago está siendo procesado.',
    subtitleCancelled: 'Esta reserva fue cancelada.',
    bookingRef: 'Referencia',
    statusLabel: 'Estado',
    experienceLabel: 'Experiencia',
    businessLabel: 'Negocio',
    date: 'Fecha',
    people: 'Personas',
    total: 'Total pagado',
    myBookings: 'Ver mis reservas',
    explore: 'Explorar más negocios',
    guideContact: 'Coordina con tu guía',
    guideContactHint: 'Escríbele por WhatsApp para confirmar el horario y punto de encuentro.',
    whatsappButton: 'Escribir por WhatsApp',
    notesLabel: 'Tus notas',
  },

  list: {
    pageTitle: 'Mis reservas',
    pageSubtitle: 'Historial de tus reservas en Manaure',
    empty: 'Aún no tienes reservas. ¡Explora las experiencias disponibles!',
    explore: 'Explorar negocios',
    date: 'Fecha',
    people: 'Personas',
    total: 'Total',
    status: {
      pending_payment: 'Pago pendiente',
      confirmed: 'Confirmada',
      cancelled: 'Cancelada',
      completed: 'Completada',
    } as Record<string, string>,
    statusColors: {
      pending_payment: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
      confirmed: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
      cancelled: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
      completed: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
    } as Record<string, string>,
  },

  errors: {
    notFound: 'Experiencia no encontrada.',
    experienceUnavailable: 'Esta experiencia no está disponible en este momento.',
    invalidPeople: 'El número de personas debe ser al menos 1.',
    capacityExceeded: 'Supera el cupo máximo de esta experiencia.',
    invalidDate: 'La fecha debe ser hoy o en el futuro.',
    generic: 'Ocurrió un error. Intenta de nuevo.',
    unauthorized: 'Debes iniciar sesión como turista para reservar.',
    rateLimited: 'Demasiadas solicitudes. Espera un momento e intenta de nuevo.',
  },
}
