export const bookingsCopy = {
  form: {
    title: 'Reservar servicio',
    date: 'Fecha',
    datePlaceholder: 'Selecciona una fecha',
    quantity: 'Cantidad',
    quantityPlaceholder: 'Ej: 2',
    totalLabel: 'Total a pagar',
    submit: 'Confirmar reserva',
    submitting: 'Procesando...',
    cancel: 'Cancelar',
    packageTitle: 'Solicitar este paquete',
    notesLabel: 'Notas (opcional)',
    notesPlaceholder: 'Ej: hora de llegada preferida, alguna necesidad especial...',
    packageSubmit: 'Solicitar disponibilidad',
    packageSubmitting: 'Enviando solicitud...',
    loginToRequest: 'Inicia sesión para solicitar este paquete',
    selectDatePrompt: 'Elige una fecha disponible en el calendario.',
    serviceTitle: 'Solicitar este servicio',
    serviceSubmit: 'Solicitar reserva',
    serviceSubmitting: 'Enviando...',
    guideTourTitle: 'Solicitar este tour',
    guideTourSubmit: 'Solicitar reserva',
    guideTourSubmitting: 'Enviando...',
    loginToRequestService: 'Inicia sesión para solicitar este servicio',
    loginToRequestGuideTour: 'Inicia sesión para solicitar este tour',
  },

  confirmation: {
    titleConfirmed: '¡Reserva confirmada!',
    titlePending: 'Reserva en proceso',
    titlePendingAvailability: 'Solicitud recibida',
    titleCancelled: 'Reserva cancelada',
    subtitleConfirmed: 'Tu reserva fue registrada exitosamente.',
    subtitlePending: 'Tu pago está siendo procesado.',
    subtitlePendingAvailability:
      'Estamos confirmando disponibilidad con los proveedores. Te contactaremos por WhatsApp o correo.',
    subtitleCancelled: 'Esta reserva fue cancelada.',
    bookingRef: 'Referencia',
    statusLabel: 'Estado',
    serviceLabel: 'Servicio',
    businessLabel: 'Negocio',
    packageLabel: 'Paquete',
    date: 'Fecha',
    quantity: 'Cantidad',
    total: 'Total pagado',
    myBookings: 'Ver mis reservas',
    explore: 'Explorar más negocios',
    guideContact: 'Coordina con tu guía',
    guideContactHint: 'Escríbele por WhatsApp para confirmar el horario y punto de encuentro.',
    whatsappButton: 'Escribir por WhatsApp',
    notesLabel: 'Tus notas',
  },

  list: {
    pageTitle: 'Mis reservas',
    pageSubtitle: 'Historial de tus reservas en Manaure',
    empty: 'Aún no tienes reservas. ¡Explora los servicios disponibles!',
    explore: 'Explorar negocios',
    date: 'Fecha',
    quantity: 'Cantidad',
    total: 'Total',
    status: {
      pending_availability: 'Confirmando disponibilidad',
      pending_payment: 'Pago pendiente',
      confirmed: 'Confirmada',
      cancelled: 'Cancelada',
      completed: 'Completada',
    } as Record<string, string>,
    statusColors: {
      pending_availability: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-400',
      pending_payment: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
      confirmed: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
      cancelled: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
      completed: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
    } as Record<string, string>,
  },

  errors: {
    notFound: 'No se encontró el servicio o tour seleccionado.',
    packageNotFound: 'No se encontró el paquete seleccionado.',
    unavailable: 'Esto no está disponible en este momento.',
    invalidQuantity: 'La cantidad debe ser al menos 1.',
    capacityExceeded: 'Supera el cupo máximo disponible.',
    invalidDate: 'La fecha debe ser hoy o en el futuro.',
    generic: 'Ocurrió un error. Intenta de nuevo.',
    unauthorized: 'Debes iniciar sesión como turista para reservar.',
    rateLimited: 'Demasiadas solicitudes. Espera un momento e intenta de nuevo.',
  },

  refund: {
    requestButton: 'Solicitar reembolso',
    reasonLabel: 'Motivo (opcional)',
    reasonPlaceholder: 'Cuéntanos por qué cancelas',
    confirm: 'Confirmar solicitud',
    confirming: 'Enviando...',
    cancel: 'Cancelar',
    disclaimer:
      'El porcentaje de reembolso depende de cuánto falte para la fecha reservada.',
    disclaimerFee:
      'Si el reembolso no se procesa el mismo día del pago, se descuenta la comisión no reembolsable de la pasarela de pago del monto que recibes.',
    payoutInstructionsLabel: '¿Cómo quieres recibir tu reembolso?',
    payoutInstructionsPlaceholder: 'Ej: Nequi 300 000 0000, o cuenta de ahorros Bancolombia a nombre de...',
    payoutInstructionsHintOptional:
      'Si tu pago no califica para reverso automático a tu tarjeta, usaremos esto para transferirte el dinero. Opcional, pero te ahorra que te contactemos después.',
    payoutInstructionsHintRequired:
      'Tu reembolso no puede procesarse automáticamente — necesitamos esta información para transferirte el dinero.',
    status: {
      pending: 'Reembolso solicitado',
      processing: 'Reembolso en proceso',
      processed: 'Reembolso procesado',
      rejected: 'Reembolso rechazado',
    } as Record<string, string>,
    statusColors: {
      pending: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
      processing: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
      processed: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
      rejected: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
    } as Record<string, string>,
    errors: {
      notRefundable: 'Esta reserva no se puede reembolsar en su estado actual.',
      alreadyRequested: 'Ya existe una solicitud de reembolso para esta reserva.',
    },
  },

  review: {
    leaveReview: 'Dejar reseña',
    ratingLabel: '¿Cómo calificarías este tour?',
    commentLabel: 'Comentario (opcional)',
    commentPlaceholder: 'Cuéntale a otros turistas cómo fue tu experiencia...',
    submit: 'Enviar reseña',
    submitting: 'Enviando...',
    cancel: 'Cancelar',
    submitted: '¡Gracias por tu reseña!',
    alreadyReviewed: 'Ya reseñaste este tour',
    errors: {
      invalidRating: 'Selecciona una calificación de 1 a 5 estrellas.',
      notEligible: 'Solo puedes reseñar tours ya realizados de reservas confirmadas.',
      alreadyReviewed: 'Ya dejaste una reseña para esta reserva.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
    },
  },

  packageReview: {
    leaveReview: 'Dejar reseña',
    ratingLabel: '¿Cómo calificarías el paquete en general?',
    itemRatingLabel: (label: string) => `Calificación para: ${label}`,
    commentLabel: 'Comentario (opcional)',
    commentPlaceholder: 'Cuéntale a otros turistas cómo fue tu experiencia...',
    submit: 'Enviar reseña',
    submitting: 'Enviando...',
    cancel: 'Cancelar',
    submitted: '¡Gracias por tu reseña!',
    errors: {
      invalidRating: 'Selecciona una calificación de 1 a 5 estrellas.',
      notEligible: 'Solo puedes reseñar paquetes ya realizados de reservas confirmadas.',
      alreadyReviewed: 'Ya dejaste una reseña para esta reserva.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
    },
  },

  serviceReview: {
    leaveReview: 'Dejar reseña',
    ratingLabel: '¿Cómo calificarías este servicio?',
    commentLabel: 'Comentario (opcional)',
    commentPlaceholder: 'Cuéntale a otros turistas cómo fue tu experiencia...',
    submit: 'Enviar reseña',
    submitting: 'Enviando...',
    cancel: 'Cancelar',
    submitted: '¡Gracias por tu reseña!',
    errors: {
      invalidRating: 'Selecciona una calificación de 1 a 5 estrellas.',
      notEligible: 'Solo puedes reseñar servicios ya realizados de reservas confirmadas.',
      alreadyReviewed: 'Ya dejaste una reseña para esta reserva.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
    },
  },
}
