export const miNegocioCopy = {
  nav: {
    overview: 'Mi negocio',
    experiences: 'Actividades',
  },
  setup: {
    title: 'Registra tu negocio',
    subtitle: 'Completa la información para que los turistas puedan encontrarte.',
    submit: 'Crear negocio',
    submitting: 'Creando negocio...',
  },
  overview: {
    title: 'Mis negocios',
    statusLabel: 'Estado',
    statusPending: 'En revisión',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
    pendingNote: 'Tu negocio está siendo revisado por nuestro equipo. Te notificaremos cuando esté aprobado.',
    editButton: 'Editar información',
    experiencesSubtitle: 'Administra tus actividades y servicios',
    activeBookings: 'Reservas activas',
    activeBookingsNote: 'confirmadas y pendientes de pago',
  },
  experiences: {
    title: 'Mis actividades',
    addButton: 'Nueva actividad',
    newTitle: 'Nueva actividad',
    backToExperiences: 'Volver a actividades',
    empty: 'Aún no tienes actividades. Agrega una para que los turistas puedan reservar.',
    activate: 'Activar',
    deactivate: 'Desactivar',
    toggling: 'Actualizando...',
    statusActive: 'Activa',
    statusInactive: 'Inactiva',
  },
  form: {
    name: 'Nombre',
    namePlaceholder: 'Ej: Tour por el río',
    businessNamePlaceholder: 'Ej: Balneario El Paraíso',
    description: 'Descripción',
    descriptionPlaceholder: 'Describe la actividad...',
    businessDescriptionPlaceholder: 'Describe tu negocio...',
    categories: 'Categorías',
    categoriesHint: 'Selecciona todas las que aplican.',
    address: 'Dirección',
    addressPlaceholder: 'Ej: Calle 5 #10-20, Manaure',
    phone: 'Teléfono de contacto',
    phonePlaceholder: 'Ej: 3001234567',
    price: 'Precio por persona (COP)',
    pricePlaceholder: 'Ej: 50000',
    capacity: 'Cupo máximo',
    capacityPlaceholder: 'Ej: 10',
    duration: 'Duración (minutos)',
    durationPlaceholder: 'Ej: 90',
    submit: 'Guardar',
    submitting: 'Guardando...',
    save: 'Guardar cambios',
    saving: 'Guardando...',
    cancel: 'Cancelar',
  },
  errors: {
    generic: 'Ocurrió un error. Intenta de nuevo.',
  },
}

export const businessesCopy = {
  nav: {
    businesses: 'Explorar',
    places: 'Lugares',
    experiences: 'Actividades',
  },

  businesses: {
    pageTitle: 'Explora Manaure',
    pageSubtitle: 'Descubre los mejores balnearios, restaurantes y fincas de Manaure',
    empty: 'Próximamente habrá establecimientos disponibles en Manaure.',
    fromPrice: 'Desde',
    viewDetail: 'Ver detalles',
    types: {
      resort: 'Balneario',
      restaurant: 'Restaurante',
      farm: 'Finca',
      eatery: 'Estadero',
      other: 'Otro',
    } as Record<string, string>,
  },

  places: {
    pageTitle: 'Imperdibles de Manaure',
    pageSubtitle: 'Los lugares que todo visitante debe conocer en Manaure Balcón del Cesar',
    empty: 'Próximamente se publicarán los imperdibles de Manaure.',
    types: {
      waterfall: 'Cascada',
      river: 'Río',
      viewpoint: 'Mirador',
      plaza: 'Plaza',
      park: 'Parque',
      other: 'Lugar de interés',
    } as Record<string, string>,
  },

  experiences: {
    sectionTitle: 'Actividades disponibles',
    empty: 'Este establecimiento no tiene actividades disponibles por el momento.',
    book: 'Reservar',
    bookGuest: 'Inicia sesión para reservar',
    duration: 'Duración',
    capacity: 'Cupo',
    minutes: 'min',
    people: 'personas',
    price: 'Precio por persona',
  },

  detail: {
    contact: 'Contacto',
    address: 'Dirección',
    back: 'Volver',
  },
}
