export const miNegocioCopy = {
  nav: {
    overview: 'Mi negocio',
    services: 'Servicios',
  },
  setup: {
    title: 'Registra tu negocio',
    subtitle: 'Completa la información para que los turistas puedan encontrarte.',
    submit: 'Crear negocio',
    submitting: 'Creando negocio...',
  },
  overview: {
    title: 'Mis negocios',
    statusLabel: 'Estado',
    statusPending: 'En revisión',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
    pendingNote: 'Tu negocio está siendo revisado por nuestro equipo. Te notificaremos cuando esté aprobado.',
    editButton: 'Editar información',
    experiencesSubtitle: 'Administra tus servicios',
    activeBookings: 'Reservas activas',
    activeBookingsNote: 'confirmadas y pendientes de pago',
  },
  services: {
    title: 'Mis servicios',
    addButton: 'Nuevo servicio',
    newTitle: 'Nuevo servicio',
    editTitle: 'Editar servicio',
    editButton: 'Editar',
    editDetails: 'Detalles',
    editImages: 'Fotos y videos',
    editImagesHint: 'La primera foto es la portada. Máximo 10 fotos y videos.',
    saved: 'Cambios guardados.',
    backToServices: 'Volver a servicios',
    empty: 'Aún no tienes servicios. Agrega uno para que los turistas puedan reservar.',
    activate: 'Activar',
    deactivate: 'Desactivar',
    toggling: 'Actualizando...',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
    typeLabel: 'Tipo de servicio',
    typeHint: 'Elige el tipo de servicio. No se puede cambiar después de creado.',
  },
  form: {
    name: 'Nombre',
    namePlaceholder: 'Ej: Tour por el río',
    businessNamePlaceholder: 'Ej: Balneario El Paraíso',
    description: 'Descripción',
    descriptionPlaceholder: 'Describe el servicio...',
    businessDescriptionPlaceholder: 'Describe tu negocio...',
    categories: 'Categorías',
    categoriesHint: 'Selecciona todas las que aplican.',
    address: 'Dirección',
    addressPlaceholder: 'Ej: Calle 5 #10-20, Manaure',
    location: 'Ubicación',
    locationHint: 'Tocá el mapa para marcar dónde queda tu negocio.',
    phone: 'Teléfono de contacto',
    phonePlaceholder: 'Ej: 3001234567',
    pricePlaceholder: 'Ej: 50000',
    capacity: 'Cupo máximo',
    capacityPlaceholder: 'Ej: 10',
    submit: 'Guardar',
    submitting: 'Guardando...',
    save: 'Guardar cambios',
    saving: 'Guardando...',
    cancel: 'Cancelar',
    rntNumber: 'Número de Registro Nacional de Turismo (RNT)',
    rntNumberPlaceholder: 'Ej: 12345',
    rntDocument: 'Certificado RNT (PDF o foto)',
    rntDocumentHint: 'Descárgalo en rnt.confecamaras.co. El equipo de ManTur lo verificará antes de activar el negocio.',
    rntSectionTitle: 'Registro Nacional de Turismo',
    rntCurrentStatus: 'Estado actual',
    rntUpdateHint: 'Solo sube un archivo si necesitas actualizar tu RNT (ej. venció y ya lo renovaste). Si no, deja esto en blanco.',
    rntStatusLabels: {
      pending_review: 'En revisión',
      verified: 'Verificado',
      rejected: 'Rechazado',
    } as Record<string, string>,
  },
  errors: {
    generic: 'Ocurrió un error. Intenta de nuevo.',
    rntNumberRequired: 'El número de RNT es obligatorio.',
    rntDocumentRequired: 'Adjunta el certificado RNT.',
    invalidDocument: 'Formato no válido. Usa PDF, JPEG, PNG o WebP.',
    documentTooLarge: 'El archivo no puede superar 8 MB.',
    uploadFailed: 'No se pudo subir el documento. Intenta de nuevo.',
  },
  payout: {
    title: 'Cuenta para pagos',
    subtitle: 'A esta cuenta se transfiere tu parte de cada reserva pagada (el monto menos la comisión de ManTur).',
    bankName: 'Banco',
    bankNamePlaceholder: 'Ej: Bancolombia',
    accountType: 'Tipo de cuenta',
    accountTypeOptions: {
      ahorros: 'Ahorros',
      corriente: 'Corriente',
    } as Record<string, string>,
    accountNumber: 'Número de cuenta',
    accountNumberPlaceholder: 'Ej: 00011122233',
    holderIdType: 'Tipo de documento del titular',
    holderIdTypeOptions: {
      CC: 'Cédula de ciudadanía',
      CE: 'Cédula de extranjería',
      NIT: 'NIT',
    } as Record<string, string>,
    holderIdNumber: 'Número de documento del titular',
    holderName: 'Nombre del titular',
    holderNamePlaceholder: 'Nombre completo o razón social',
    holderEmail: 'Correo del titular',
    holderEmailPlaceholder: 'correo@ejemplo.com',
    save: 'Guardar cuenta',
    saving: 'Guardando...',
    saved: 'Cuenta de pagos guardada.',
  },
}

export const businessesCopy = {
  nav: {
    businesses: 'Explorar',
    places: 'Lugares',
    services: 'Servicios',
  },

  businesses: {
    pageTitle: 'Explora Manaure',
    pageSubtitle: 'Descubre los mejores balnearios, restaurantes y fincas de Manaure',
    filterLabel: 'Filtrar por tipo',
    listLabel: 'Lista',
    mapLabel: 'Mapa',
    empty: 'Próximamente habrá establecimientos disponibles en Manaure.',
    fromPrice: 'Desde',
    viewDetail: 'Ver detalles',
    types: {
      resort: 'Balneario',
      restaurant: 'Restaurante',
      farm: 'Finca',
      eatery: 'Estadero',
      other: 'Otro',
    } as Record<string, string>,
  },

  places: {
    pageTitle: 'Imperdibles de Manaure',
    pageSubtitle: 'Los lugares que todo visitante debe conocer en Manaure Balcón del Cesar',
    filterLabel: 'Filtrar por tipo',
    empty: 'Próximamente se publicarán los imperdibles de Manaure.',
    viewMap: 'Ver en el mapa',
    listLabel: 'Lista',
    mapLabel: 'Mapa',
    nearbyBusinessesTitle: 'Negocios cerca de este lugar',
    similarPlacesTitle: 'Otros lugares imperdibles',
    types: {
      waterfall: 'Cascada',
      river: 'Río',
      viewpoint: 'Mirador',
      plaza: 'Plaza',
      park: 'Parque',
      other: 'Lugar de interés',
    } as Record<string, string>,
  },

  services: {
    sectionTitle: 'Servicios disponibles',
    empty: 'Este establecimiento no tiene servicios disponibles por el momento.',
    book: 'Reservar',
    bookGuest: 'Inicia sesión para reservar',
    duration: 'Duración',
    capacity: 'Cupo',
    minutes: 'min',
    people: 'personas',
    price: 'Precio',
  },

  detail: {
    contact: 'Contacto',
    address: 'Dirección',
    back: 'Volver',
  },
}
