export const guidesCopy = {
  publicPage: {
    pageTitle: 'Guías turísticos locales',
    pageSubtitle: 'Conoce Manaure de la mano de expertos locales',
    available: 'Disponible',
    availableNowLabel: 'guías disponibles',
    availableNowLabelSingular: 'guía disponible',
    empty: 'No hay guías disponibles en este momento.',
    specialtiesLabel: 'Especialidades',
    languagesLabel: 'Idiomas',
    tours: 'tours',
  },

  profilePage: {
    available: 'Disponible',
    notAvailable: 'No disponible',
    specialtiesLabel: 'Especialidades',
    languagesLabel: 'Idiomas',
    toursTitle: 'Tours disponibles',
    noTours: 'Este guía aún no tiene tours publicados.',
    bookTour: 'Reservar tour',
    duration: 'min',
    people: 'personas (máx.)',
  },

  bookingForm: {
    title: 'Reservar tour',
    tourLabel: 'Tour',
    peopleCount: 'Número de personas',
    bookingDate: 'Fecha del tour',
    pricePerPerson: 'Precio por persona',
    totalLabel: 'Total estimado',
    notesLabel: 'Notas para el guía',
    notesPlaceholder: 'Ej: Prefiero ir en la mañana, ¿puedes pasar por la plaza?',
    notesOptional: '(opcional)',
    submit: 'Confirmar reserva',
    submitting: 'Procesando...',
  },

  guidePanel: {
    pageTitle: 'Mi perfil de guía',
    availabilityLabel: 'Disponible para tours',
    bioLabel: 'Bio',
    specialtiesLabel: 'Especialidades',
    languagesLabel: 'Idiomas',
    toursSection: 'Mis tours',
    addTour: 'Agregar tour',
    emptyTours: 'Aún no tienes tours. ¡Crea el primero!',
    bookingsSection: 'Reservas recientes',
    emptyBookings: 'No tienes reservas aún.',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
    editTour: 'Editar',
    toggleActive: 'Activar',
    toggleInactive: 'Desactivar',
    available: 'Disponible',
    notAvailable: 'No disponible',
    tourist: 'Turista',
    bookingDate: 'Fecha',
    people: 'personas',
    total: 'Total',
    notesLabel: 'Notas del turista',
  },

  editProfile: {
    pageTitle: 'Editar perfil',
    phone: 'Teléfono de contacto (WhatsApp)',
    phonePlaceholder: 'Ej: 300 123 4567',
    bio: 'Bio',
    bioPlaceholder: 'Cuéntale a los turistas sobre tu experiencia y estilo de guía...',
    specialties: 'Especialidades',
    languages: 'Idiomas',
    save: 'Guardar cambios',
    saving: 'Guardando...',
    saved: '¡Perfil actualizado!',
    back: 'Volver a mi panel',
  },

  tourForm: {
    createTitle: 'Nuevo tour',
    editTitle: 'Editar tour',
    detailsSection: 'Detalles',
    imagesSection: 'Fotos',
    name: 'Nombre del tour',
    namePlaceholder: 'Ej: Caminata a las cascadas del Perijá',
    description: 'Descripción',
    descriptionPlaceholder: 'Describe la experiencia, qué incluye, qué traer...',
    price: 'Precio por persona (COP)',
    pricePlaceholder: 'Ej: 50000',
    capacity: 'Capacidad máxima de personas',
    capacityPlaceholder: 'Ej: 10',
    duration: 'Duración (minutos)',
    durationPlaceholder: 'Ej: 180',
    save: 'Guardar tour',
    saving: 'Guardando...',
    saved: 'Cambios guardados.',
    imagesHint: 'Agrega hasta 5 fotos. Se mostrarán en tu perfil público.',
    backToPanel: 'Volver a mi panel',
  },

  errors: {
    nameRequired: 'El nombre del tour es obligatorio.',
    priceInvalid: 'El precio debe ser un número mayor o igual a 0.',
    capacityInvalid: 'La capacidad debe ser un número entero positivo.',
    generic: 'Ocurrió un error. Intenta de nuevo.',
    unauthorized: 'Debes tener el rol de guía turístico.',
    notFound: 'Tour no encontrado.',
    tourUnavailable: 'Este tour no está disponible para reserva.',
    invalidPeople: 'El número de personas no es válido.',
    capacityExceeded: 'No hay suficiente capacidad en este tour.',
    invalidDate: 'La fecha debe ser hoy o en el futuro.',
    invalidPhone: 'Escribe un número de celular colombiano válido (10 dígitos, ej: 300 123 4567).',
  },
} as const
