import { CALENDAR_WEEKDAYS, CALENDAR_MONTHS, calendarActionLabels, calendarGenericErrors } from './calendar'

export const transportCopy = {
  publicPage: {
    pageTitle: 'Transportadores disponibles',
    pageSubtitle: 'Movilízate por Manaure con conductores locales de confianza',
    empty: 'No hay transportadores disponibles en este momento.',
    available: 'Disponible',
    notAvailable: 'No disponible',
    availableNowLabel: 'disponibles ahora',
    availableNowLabelSingular: 'disponible ahora',
    filterAvailable: 'Disponibles ahora',
    filterAll: 'Todos',
    requestRide: 'Solicitar traslado',
    modalTitle: 'Solicitar traslado',
    modalDriverLabel: 'Conductor',
    modalNote: 'Tu solicitud estará disponible para todos los conductores activos.',
    vehicleTypes: {
      motocarro: 'Motocarro',
      moto:      'Moto',
      camioneta: 'Camioneta',
      otro:      'Otro',
    } as Record<string, string>,
  },

  requestForm: {
    pageTitle: 'Solicitar traslado',
    pageSubtitle: 'Un conductor local te llevará a tu destino',
    routeLabel: 'Ruta (opcional)',
    customRouteOption: '— Traslado personalizado —',
    tripTypeLabel: '¿Ida o ida y vuelta?',
    oneWayLabel: 'Solo ida',
    roundTripLabel: 'Ida y vuelta',
    origin: 'Punto de recogida',
    originPlaceholder: 'Ej: Hotel El Paraíso, calle 5 #10-20',
    destination: 'Destino',
    destinationPlaceholder: 'Ej: Balneario El Edén, vereda Los Colorados',
    requestedDatetime: 'Fecha y hora',
    peopleCount: 'Número de personas',
    notes: 'Información adicional (opcional)',
    notesPlaceholder: 'Ej: Llevamos equipaje grande, somos 2 adultos y 1 niño...',
    submit: 'Enviar solicitud',
    submitting: 'Enviando...',
    successTitle: '¡Solicitud enviada!',
  },

  myTrips: {
    pageTitle: 'Mis traslados',
    pageSubtitle: 'Historial de tus solicitudes de transporte en Manaure',
    empty: 'Aún no tienes solicitudes de transporte. ¡Explora los transportadores disponibles!',
    explore: 'Ver transportadores',
    origin: 'Desde',
    destination: 'Hasta',
    datetime: 'Fecha y hora',
    people: 'personas',
    cancel: 'Cancelar',
    cancelling: 'Cancelando...',
    transporter: 'Transportador',
    phone: 'Teléfono',
    vehicle: 'Vehículo',
    status: {
      pending:   'Pendiente',
      accepted:  'Aceptada',
      completed: 'Completada',
      cancelled: 'Cancelada',
    } as Record<string, string>,
    statusColors: {
      pending:   'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
      accepted:  'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
      completed: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
      cancelled: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
    } as Record<string, string>,
  },

  review: {
    leaveReview: 'Dejar reseña',
    ratingLabel: '¿Cómo calificarías este traslado?',
    commentLabel: 'Comentario (opcional)',
    commentPlaceholder: 'Cuéntale a otros turistas cómo fue tu experiencia...',
    submit: 'Enviar reseña',
    submitting: 'Enviando...',
    cancel: 'Cancelar',
    submitted: '¡Gracias por tu reseña!',
    errors: {
      invalidRating: 'Selecciona una calificación de 1 a 5 estrellas.',
      notEligible: 'Solo puedes reseñar traslados ya completados.',
      alreadyReviewed: 'Ya dejaste una reseña para este traslado.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
      rateLimited: 'Demasiadas solicitudes. Espera un momento e intenta de nuevo.',
    },
  },

  reviews: {
    noReviewsYet: 'Aún no tiene reseñas.',
    reviewCount: (n: number) => (n === 1 ? '1 reseña' : `${n} reseñas`),
  },

  transporterPanel: {
    pageTitle: 'Mi panel de transporte',
    profileCard: {
      title: 'Tu perfil',
      availabilityLabel: 'Disponible para traslados',
      licenseLabel: 'Placa',
      phoneLabel: 'Teléfono',
      bioLabel: 'Descripción',
      editDocuments: 'Actualizar mis documentos',
    },
    pendingRequests: {
      title: 'Solicitudes disponibles',
      empty: 'No hay solicitudes pendientes por el momento.',
      accept: 'Aceptar traslado',
      accepting: 'Aceptando...',
      origin: 'Desde',
      destination: 'Hasta',
      datetime: 'Fecha y hora',
      people: 'personas',
      notes: 'Notas del turista',
      tourist: 'Turista',
    },
    activeRequests: {
      title: 'Mis traslados aceptados',
      empty: 'No tienes traslados en curso.',
      complete: 'Marcar completado',
      completing: 'Guardando...',
    },
    errors: {
      alreadyAccepted: 'Esta solicitud ya fue aceptada por otro transportador.',
      notFound: 'Solicitud no encontrada.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
      unauthorized: 'Debes tener el rol de transportador.',
    },
  },

  payout: {
    title: 'Cuenta para pagos',
    subtitle: 'A esta cuenta se transfiere tu parte de cada traslado pagado (el monto menos la comisión de ManTur).',
    bankName: 'Banco',
    bankSelectPlaceholder: '— Selecciona un banco —',
    banksLoadError: 'No pudimos cargar la lista de bancos de Wompi. Intenta de nuevo.',
    retry: 'Reintentar',
    accountType: 'Tipo de cuenta',
    accountTypePlaceholder: '— Selecciona un tipo de cuenta —',
    accountTypeOptions: {
      ahorros: 'Ahorros',
      corriente: 'Corriente',
    } as Record<string, string>,
    accountNumber: 'Número de cuenta',
    accountNumberPlaceholder: 'Ej: 00011122233',
    holderIdType: 'Tipo de documento del titular',
    holderIdTypePlaceholder: '— Selecciona un tipo de documento —',
    holderIdTypeOptions: {
      CC: 'Cédula de ciudadanía',
      CE: 'Cédula de extranjería',
      NIT: 'NIT',
    } as Record<string, string>,
    holderIdNumber: 'Número de documento del titular',
    holderName: 'Nombre del titular',
    holderNamePlaceholder: 'Nombre completo',
    holderEmail: 'Correo del titular',
    holderEmailPlaceholder: 'correo@ejemplo.com',
    save: 'Guardar cuenta',
    saving: 'Guardando...',
    saved: 'Cuenta de pagos guardada.',
  },

  acceptForm: {
    priceLabel: 'Precio del traslado (COP, opcional)',
    pricePlaceholder: 'Ej: 25000',
  },

  editProfile: {
    pageTitle: 'Actualizar mis documentos',
    back: 'Volver a mi panel',
    save: 'Guardar cambios',
    saving: 'Guardando...',
    saved: '¡Documentos actualizados!',
    currentStatus: 'Estado actual',
    statusLabels: {
      pending_review: 'En revisión',
      verified: 'Verificado',
      rejected: 'Rechazado',
    } as Record<string, string>,
    tierChangeRequiresDocument: 'Adjunta el documento correspondiente para cambiar de modalidad.',
  },

  adminPage: {
    pageTitle: 'Traslados',
    pageSubtitle: 'Gestión de solicitudes de transporte',
    origin: 'Desde',
    destination: 'Hasta',
    tourist: 'Turista',
    transporter: 'Transportador',
    datetime: 'Fecha y hora',
    people: 'personas',
    unassigned: 'Sin asignar',
    status: {
      pending:   'Pendiente',
      accepted:  'Aceptada',
      completed: 'Completada',
      cancelled: 'Cancelada',
    } as Record<string, string>,
    statusColors: {
      pending:   'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
      accepted:  'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
      completed: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
      cancelled: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
    } as Record<string, string>,
  },

  errors: {
    invalidDatetime: 'La fecha y hora deben ser en el futuro.',
    missingFields: 'Completa todos los campos requeridos.',
    generic: 'Ocurrió un error. Intenta de nuevo.',
    unauthorized: 'Debes iniciar sesión como turista para solicitar transporte.',
    requestNotFound: 'Solicitud no encontrada.',
    rateLimited: 'Demasiadas solicitudes. Espera un momento e intenta de nuevo.',
  },

  availability: {
    title: 'Disponibilidad general',
    subtitle: 'Marca los días en que no puedes atender traslados. Los días sin marcar se asumen disponibles, y esto se hereda automáticamente a todas tus rutas.',
    backToPanel: 'Volver a mi panel',
    ...calendarActionLabels,
    weekdays: CALENDAR_WEEKDAYS,
    months: CALENDAR_MONTHS,
    weeklyPatternTitle: 'Patrón semanal',
    weeklyPatternSubtitle: 'Si normalmente no atiendes traslados ciertos días de la semana, márcalos aquí una sola vez. Las marcas puntuales del calendario de abajo siempre tienen prioridad sobre este patrón.',
    errors: {
      notFound: 'Transportador no encontrado.',
      ...calendarGenericErrors,
    },
  },

  routeAvailability: {
    title: 'Disponibilidad de la ruta',
    subtitle: 'Marca los días en que esta ruta en particular no está disponible. Los días sin marcar se asumen disponibles, salvo que tu calendario general te marque como no disponible ese día.',
    backToRoutes: 'Volver a mis rutas',
    ...calendarActionLabels,
    weekdays: CALENDAR_WEEKDAYS,
    months: CALENDAR_MONTHS,
    errors: {
      notFound: 'Ruta no encontrada.',
      ...calendarGenericErrors,
    },
  },

  routes: {
    title: 'Mis rutas',
    addButton: 'Nueva ruta',
    newTitle: 'Nueva ruta',
    editTitle: 'Editar ruta',
    editButton: 'Editar',
    availabilityButton: 'Disponibilidad',
    empty: 'Aún no tienes rutas publicadas. Agrega una para que los turistas la vean.',
    activate: 'Activar',
    deactivate: 'Desactivar',
    toggling: 'Actualizando...',
    statusActive: 'Activa',
    statusInactive: 'Inactiva',
    saved: 'Cambios guardados.',
    backToPanel: 'Volver a mi panel',
    form: {
      origin: 'Origen',
      originPlaceholder: 'Ej: Casco urbano de Manaure',
      destination: 'Destino',
      destinationPlaceholder: 'Ej: Balneario El Edén, vereda Los Colorados',
      modalitiesLabel: '¿Qué modalidades ofreces en esta ruta?',
      allowOneWay: 'Solo ida',
      allowRoundTrip: 'Ida y vuelta',
      priceOneWay: 'Precio ida (COP, opcional)',
      priceOneWayPlaceholder: 'Ej: 15000',
      priceRoundTrip: 'Precio ida y vuelta (COP, opcional)',
      priceRoundTripPlaceholder: 'Ej: 25000',
      pricingHint: 'Deja el precio en blanco si prefieres cotizarlo al aceptar cada solicitud.',
      duration: 'Duración estimada (minutos, opcional)',
      durationPlaceholder: 'Ej: 20',
      notes: 'Notas (opcional)',
      notesPlaceholder: 'Ej: solo en temporada seca, requiere reserva con un día de anticipación...',
      submit: 'Guardar ruta',
      submitting: 'Guardando...',
      cancel: 'Cancelar',
    },
    errors: {
      notFound: 'Ruta no encontrada.',
      missingFields: 'El origen y el destino son obligatorios.',
      noModality: 'Selecciona al menos una modalidad (ida o ida y vuelta).',
      invalidPrice: 'El precio debe ser un número positivo.',
      invalidDuration: 'La duración debe ser un número positivo.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
    },
  },
} as const
