export const transportCopy = {
  publicPage: {
    pageTitle: 'Transportadores disponibles',
    pageSubtitle: 'Movilízate por Manaure con conductores locales de confianza',
    empty: 'No hay transportadores disponibles en este momento.',
    available: 'Disponible',
    requestRide: 'Solicitar traslado',
    modalTitle: 'Solicitar traslado',
    modalDriverLabel: 'Conductor',
    modalNote: 'Tu solicitud estará disponible para todos los conductores activos.',
    vehicleTypes: {
      motocarro: 'Motocarro',
      moto:      'Moto',
      camioneta: 'Camioneta',
      otro:      'Otro',
    } as Record<string, string>,
  },

  requestForm: {
    pageTitle: 'Solicitar traslado',
    pageSubtitle: 'Un conductor local te llevará a tu destino',
    origin: 'Punto de recogida',
    originPlaceholder: 'Ej: Hotel El Paraíso, calle 5 #10-20',
    destination: 'Destino',
    destinationPlaceholder: 'Ej: Balneario El Edén, vereda Los Colorados',
    requestedDatetime: 'Fecha y hora',
    peopleCount: 'Número de personas',
    notes: 'Información adicional (opcional)',
    notesPlaceholder: 'Ej: Llevamos equipaje grande, somos 2 adultos y 1 niño...',
    submit: 'Enviar solicitud',
    submitting: 'Enviando...',
    successTitle: '¡Solicitud enviada!',
  },

  myTrips: {
    pageTitle: 'Mis traslados',
    pageSubtitle: 'Historial de tus solicitudes de transporte en Manaure',
    empty: 'Aún no tienes solicitudes de transporte. ¡Explora los transportadores disponibles!',
    explore: 'Ver transportadores',
    origin: 'Desde',
    destination: 'Hasta',
    datetime: 'Fecha y hora',
    people: 'personas',
    cancel: 'Cancelar',
    cancelling: 'Cancelando...',
    transporter: 'Transportador',
    phone: 'Teléfono',
    vehicle: 'Vehículo',
    status: {
      pending:   'Pendiente',
      accepted:  'Aceptada',
      completed: 'Completada',
      cancelled: 'Cancelada',
    } as Record<string, string>,
    statusColors: {
      pending:   'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
      accepted:  'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
      completed: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
      cancelled: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
    } as Record<string, string>,
  },

  transporterPanel: {
    pageTitle: 'Mi panel de transporte',
    profileCard: {
      title: 'Tu perfil',
      availabilityLabel: 'Disponible para traslados',
      licenseLabel: 'Placa',
      phoneLabel: 'Teléfono',
      bioLabel: 'Descripción',
    },
    pendingRequests: {
      title: 'Solicitudes disponibles',
      empty: 'No hay solicitudes pendientes por el momento.',
      accept: 'Aceptar traslado',
      accepting: 'Aceptando...',
      origin: 'Desde',
      destination: 'Hasta',
      datetime: 'Fecha y hora',
      people: 'personas',
      notes: 'Notas del turista',
      tourist: 'Turista',
    },
    activeRequests: {
      title: 'Mis traslados aceptados',
      empty: 'No tienes traslados en curso.',
      complete: 'Marcar completado',
      completing: 'Guardando...',
    },
    errors: {
      alreadyAccepted: 'Esta solicitud ya fue aceptada por otro transportador.',
      notFound: 'Solicitud no encontrada.',
      generic: 'Ocurrió un error. Intenta de nuevo.',
      unauthorized: 'Debes tener el rol de transportador.',
    },
  },

  adminPage: {
    pageTitle: 'Traslados',
    pageSubtitle: 'Gestión de solicitudes de transporte',
    origin: 'Desde',
    destination: 'Hasta',
    tourist: 'Turista',
    transporter: 'Transportador',
    datetime: 'Fecha y hora',
    people: 'personas',
    unassigned: 'Sin asignar',
    status: {
      pending:   'Pendiente',
      accepted:  'Aceptada',
      completed: 'Completada',
      cancelled: 'Cancelada',
    } as Record<string, string>,
    statusColors: {
      pending:   'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400',
      accepted:  'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400',
      completed: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400',
      cancelled: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
    } as Record<string, string>,
  },

  errors: {
    invalidDatetime: 'La fecha y hora deben ser en el futuro.',
    missingFields: 'Completa todos los campos requeridos.',
    generic: 'Ocurrió un error. Intenta de nuevo.',
    unauthorized: 'Debes iniciar sesión como turista para solicitar transporte.',
    requestNotFound: 'Solicitud no encontrada.',
    rateLimited: 'Demasiadas solicitudes. Espera un momento e intenta de nuevo.',
  },
} as const
